export const carsArray = [
  {
    make: "Hyundai",
    model: "I-10",
    year: 2023,
    seatAmount: 5,
    pricePerDay: 40,
    gear: "Manual",
    doors: 4,
    image: "https://noam-moskowitz.github.io/premium-cars-images/cars/hyundai_I10.png",
  },
  {
    make: "Hyundai",
    model: "Ionic 6",
    year: 2024,
    seatAmount: 5,
    pricePerDay: 55,
    gear: "Automatic",
    doors: 4,
    image: "https://noam-moskowitz.github.io/premium-cars-images/cars/hyundai_Ionic.png",
  },
  {
    make: "Hyundai",
    model: "Bayon",
    year: 2024,
    seatAmount: 5,
    pricePerDay: 58,
    gear: "Automatic",
    doors: 4,
    image: "https://noam-moskowitz.github.io/premium-cars-images/cars/hyundai_bayon.png",
  },
  {
    make: "Hyundai",
    model: "Elantra",
    year: 2023,
    seatAmount: 5,
    pricePerDay: 43,
    gear: "Automatic",
    doors: 4,
    image: "https://noam-moskowitz.github.io/premium-cars-images/cars/hyundai_elantra.png",
  },
  {
    make: "Hyundai",
    model: "Kona",
    year: 2024,
    seatAmount: 5,
    pricePerDay: 62,
    gear: "Automatic",
    doors: 4,
    image: "https://noam-moskowitz.github.io/premium-cars-images/cars/hyundai_kona.png",
  },
  {
    make: "Seat",
    model: "Arona",
    year: 2024,
    seatAmount: 5,
    pricePerDay: 70,
    gear: "Automatic",
    doors: 4,
    image: "https://noam-moskowitz.github.io/premium-cars-images/cars/seat_arona.png",
  },
  {
    make: "Seat",
    model: "Ateca",
    year: 2023,
    seatAmount: 5,
    pricePerDay: 74,
    gear: "Automatic",
    doors: 4,
    image: "https://noam-moskowitz.github.io/premium-cars-images/cars/seat_ateca.png",
  },
  {
    make: "Seat",
    model: "Ibiza",
    year: 2024,
    seatAmount: 5,
    pricePerDay: 68,
    gear: "Manual",
    doors: 4,
    image: "https://noam-moskowitz.github.io/premium-cars-images/cars/seat_ibiza.png",
  },
];
